name = "cardano-foundation/hydra-voting-poc"
version = "0.0.1"
licences = []
description = "Hydra Voting PoC"

dependencies = [
  { name = "Cardano-Fans/acca", version = "7fa74a150150920efa4f8e23f7f80715ef071b3a", source = "github" }
]