name = "cardano-foundation/hydra-voting-poc"
version = "0.0.1"
licences = []
description = "Hydra Voting PoC"

dependencies = [
  { name = "Cardano-Fans/acca", version = "856885b5dccecc296042e903ed442038452cf813", source = "github" }
]