name = "cardano-foundation/hydra-voting-poc"
version = "0.0.1"
licences = []
description = "Hydra Voting PoC"

dependencies = [
  { name = "aiken-lang/stdlib", version = "3b47c89006e7580c2213370d7426ed2a38d2836e", source = "github" }
]
