name = "cardano-foundation/hydra-voting-poc"
version = "0.0.1"
licences = []
description = "Hydra Voting PoC"

dependencies = [
  { name = "Cardano-Fans/acca", version = "547d9f2381634ef40cb138455a9bcacb31bd829f", source = "github" }
]