name = "cardano-foundation/hydra-voting-poc"
version = "0.0.1"
licences = []
description = "Hydra Voting PoC"

dependencies = [
  { name = "aiken-lang/stdlib", version = "288d05b0d1421eafe936010ff96e885164e8a7bd", source = "github" }
]
